[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -O2
lib_deps =

[env:esp32dev-debug]
extends = env:esp32dev
build_type = debug
build_flags =
    -DCORE_DEBUG_LEVEL=5
    -Og
    -g
